### ISSUE TITLE
pip install failure

### ISSUE THREAD

**Issue by rithal** [stephan-hof/pyrocksdb#16]
On Ubuntu 12.04, after following the instructions at http://pyrocksdb.readthedocs.org/en/latest/installation.html to build rocksdb and pyrocksdb, the following error is seen at the last step (pip install git+git…). The installation aborts.

(rdbtest)[rithal@rithal-ubuntu64 ~/rdbtest]$ pip install git+git://github.com/stephan-hof/pyrocksdb.git
Downloading/unpacking git+git://github.com/stephan-hof/pyrocksdb.git
  Cloning git://github.com/stephan-hof/pyrocksdb.git to /tmp/pip-JuTIW1-build
  Running setup.py egg_info for package from git+git://github.com/stephan-hof/pyrocksdb.git

Requirement already satisfied (use --upgrade to upgrade): setuptools in ./lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg (from pyrocksdb==0.3)
Requirement already satisfied (use --upgrade to upgrade): Cython>=0.20 in ./lib/python2.7/site-packages (from pyrocksdb==0.3)
Installing collected packages: pyrocksdb
  Running setup.py install for pyrocksdb

```
error: can't copy 'rocksdb/_rocksdb.c': doesn't exist or not a regular file
Complete output from command /home/rithal/rdbtest/bin/python -c "import setuptools;__file__='/tmp/pip-JuTIW1-build/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2AzIUx-record/install-record.txt --single-version-externally-managed --install-headers /home/rithal/rdbtest/include/site/python2.7:
running install
```

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/rocksdb

copying rocksdb/interfaces.py -> build/lib.linux-x86_64-2.7/rocksdb

copying rocksdb/errors.py -> build/lib.linux-x86_64-2.7/rocksdb

copying rocksdb/**init**.py -> build/lib.linux-x86_64-2.7/rocksdb

creating build/lib.linux-x86_64-2.7/rocksdb/tests

copying rocksdb/tests/test_options.py -> build/lib.linux-x86_64-2.7/rocksdb/tests

copying rocksdb/tests/test_db.py -> build/lib.linux-x86_64-2.7/rocksdb/tests

copying rocksdb/tests/**init**.py -> build/lib.linux-x86_64-2.7/rocksdb/tests

running egg_info

creating pyrocksdb.egg-info

writing requirements to pyrocksdb.egg-info/requires.txt

writing pyrocksdb.egg-info/PKG-INFO

writing top-level names to pyrocksdb.egg-info/top_level.txt

writing dependency_links to pyrocksdb.egg-info/dependency_links.txt

writing manifest file 'pyrocksdb.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found

reading manifest file 'pyrocksdb.egg-info/SOURCES.txt'

writing manifest file 'pyrocksdb.egg-info/SOURCES.txt'

error: can't copy 'rocksdb/_rocksdb.c': doesn't exist or not a regular file

---

Command /home/rithal/rdbtest/bin/python -c "import setuptools;**file**='/tmp/pip-JuTIW1-build/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-2AzIUx-record/install-record.txt --single-version-externally-managed --install-headers /home/rithal/rdbtest/include/site/python2.7 failed with error code 1 in /tmp/pip-JuTIW1-build
Storing complete log in /home/rithal/.pip/pip.log

**Comment by elad** [comment]
Could be because you don't have Pyrex installed. Python 2.6 uses that, not Cython.
