### ISSUE TITLE
Enable LZ4 Compression

### ISSUE THREAD

**Issue by Downchuck** [stephan-hof/pyrocksdb#25]
LZ4 is now enabled in RocksDB (it appears).

**Comment by stephan-hof** [comment]
Hi,

I will have a look at this at the weekend. Adding a new compression option should be not too hard.

**Comment by Downchuck** [comment]
Related note, they've made snappy optional.

**Comment by stephan-hof** [comment]
Fixed with https://github.com/stephan-hof/pyrocksdb/commit/2ef04007c40be97ead9d64b0ef920fcddf42d920
