### ISSUE TITLE
rocksdb 3.x

### ISSUE THREAD

**Issue by dineshbvadhia** [stephan-hof/pyrocksdb#26]
@stefan Is rocksdb 3.x support planned for pyrocksdb?

**Comment by stephan-hof** [comment]
Well the 'trunk' is already usable with rocksdb 3.X, the recent comments there are fixing compiling errors with rocksdb 3.x. The last time I tested trunk was with rocksdb 3.9.
I agree there is no official pyrocksdb release claiming support for rocksdb 3.x. Initially my plans were to support column families, but that being a bigger change and me having not much time => Never happened so far :(
Nevertheless in the next days (weekend) I will take the current trunk and create a 0.3 release out of that.

**Comment by stephan-hof** [comment]
I made the current master to pyrocksdb version 0.3 and it works fine with rocksdb 3.11.
