### ISSUE TITLE
Support WriteBatch iterator

### ISSUE THREAD

**Issue by Downchuck** [stephan-hof/pyrocksdb#27]
WriteBatch is an iterable object, but that's not currently exposed through pyrocksdb.
It seems to just be WriteBatch.iterate(handler) from Java and Perl examples.

**Comment by Downchuck** [comment]
Mis-titled this - I don't need the WriteBatchWithIndex option -- it's just standard WriteBatch, but it has an iterable.

**Comment by stephan-hof** [comment]
Fixed with https://github.com/stephan-hof/pyrocksdb/commit/302d1a64404d6b248cae543d11696302cf624fd5.
